server:
  port: 9025
  shutdown: graceful

logging:
  level:
    root: ${APP_LOG_LEVEL:INFO}
    com.example.poc: ${APP_LOG_LEVEL:DEBUG}

spring:
  application:
    name: java-poc-oauth-jqoo-openai
  threads:
    virtual-enabled: true # virtual threads (Java 21+) enabled
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9025/.well-known/jwks.json
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:openai-dummy-key}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:secret}

jooq:
  sql-dialect: postgres

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true