package com.example.poc.jwt;

import com.example.poc.constant.Constants;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSSigner;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.SignedJWT;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.Date;

import static com.example.poc.constant.Constants.OAUTH_SCOPE_CLAIM_NAME;

/**
 * Simple token service that issues RS256 signed JWTs using the private key generated by JwkService.
 * IMPORTANT: provided just for local testing and POC purposes only.
 */
@Profile("!uat & !stage & !prod")
@Service
public final class JwtTokenService {

    private final JwkService jwkService;

    /**
     * Constructor
     *
     * @param jwkService the {@link JwkService}
     */
    public JwtTokenService(JwkService jwkService) {
        this.jwkService = jwkService;
    }

    /**
     * Generates a signed JWT with the given subject and scopes.
     *
     * @param subject the {@link} subject (sub claim)
     * @param scopes  the {@link} space separated scopes (e.g. "read write")
     * @return {@link String} compact serialized JWT
     * @throws Exception when signing fails
     */
    public String generateToken(String subject, String scopes) throws Exception {
        var rsaKey = jwkService.getRsaJwk();
        JWSSigner signer = new RSASSASigner(rsaKey.toPrivateKey());

        Instant now = Instant.now();

        JWTClaimsSet claims = new JWTClaimsSet.Builder()
            .subject(subject)
            .issueTime(Date.from(now))
            .expirationTime(Date.from(now.plusSeconds(Constants.OAUTH_TOKEN_EXPIRES_IN)))
            .claim(OAUTH_SCOPE_CLAIM_NAME, scopes)
            .issuer("http://localhost:1234567890") // optional in POC
            .build();

        SignedJWT signedJWT = new SignedJWT(
            new com.nimbusds.jose.JWSHeader.Builder(JWSAlgorithm.RS256).keyID(rsaKey.getKeyID()).build(),
            claims
        );

        signedJWT.sign(signer);

        return signedJWT.serialize();
    }
}