spring:
  datasource:
    url: 'jdbc:sqlite::memory:'
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jooq:
    sql-dialect: postgres

  ai:
    openai:
      api-key: "mock-key-for-it-tests"
      chat:
        enabled: true

logging:
  level:
    org.jooq: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG